<?php

/**
 * @file
 * Tealium iQ Integration.
 */

/**
 * Implements hook_page_attachments().
 */
function tealiumiq_page_attachments(array &$attachments) {
  // Example Code to implement tealium tags.
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if (!$is_admin) {
    $attachments['#attached']['library'][] = 'tealiumiq/tealiumiq';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function tealiumiq_page_attachments_alter(array &$attachments) {
  // Example Code to implement tealium tags.
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if (!$is_admin) {
    $tealiumiq = \Drupal::service('tealiumiq.tealiumiq');
    $tealiumiq->setUdoPropertiesFromRoute();

    $attachments['#attached']['library'][] = 'tealiumiq/tealiumiq';
    $attachments['#attached']['drupalSettings']['tealiumiq']['tealiumiq'] = [
      'utagurl' => $tealiumiq->getUtagUrl(),
      'async' => $tealiumiq->getAsync(),
    ];

    $attachments['#attached']['drupalSettings']['tealiumiq']['tealiumiq']['utagData'] = $tealiumiq->getProperties();
  }
}
