tealiumiq.settings:
  type: config_object
  label: 'Tealium iQ Settings'
  mapping:
    account:
      type: string
      label: 'Account'
    profile:
      type: string
      label: 'Profile'
    environment:
      type: string
      label: 'Environment'
    utag_async:
      type: boolean
      label: 'Utag Sync'
