tealiumiq.settings:
  type: config_object
  label: 'Tealium iQ Settings'
  mapping:
    account:
      type: string
      label: 'Account'
    profile:
      type: string
      label: 'Profile'
    environment:
      type: string
      label: 'Environment'
    async:
      type: boolean
      label: 'Utag Sync'

tealiumiq.defaults:
  type: config_object
  label: 'Tealium iQ Defaults'
  mapping:
    page_name:
      type: string
      label: 'Page Name'
    page_url:
      type: string
      label: 'Page Url'
